Ensure that Motion nodes under HashJoin with outer refers are not rescanned
Previously we fix plans with a Nested Loop join on the inner side of another Nested Loop
join, executor may produce an error:

ERROR: illegal rescan of motion node: invalid plan
HINT: Likely caused by bad NL-join, try setting enable_nestloop to off

But this error will happen with Hash Join plan, this commit adds a shield material
node on the required Hash Join outer side.